build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-gce
    when:
      branch: master

plugin:
  name: Docker
  desc: Build and Publish images to the Google Container Registry.
  type: publish
  image: plugins/drone-gce
  labels:
    - docker
    - image
    - container
